@baseUrl=http://cna-email-fw-teaching.rahtiapp.fi/

GET {{baseUrl}}

###

POST {{baseUrl}}/sendmail
Content-Type: application/json

{ 
    "to": "user@maildomain.fi", 
    "subject": "Testing rahti mail", 
    "body": "Testing rahti mail3, success?" 
}