@baseUrl=http://127.0.0.1:5000/
@token = "foo"

GET {{baseUrl}}

###

POST {{baseUrl}}/sendmail
Content-Type: application/json
Authorization: Bearer {{token}}

{ 
    "to": "user@server.fi", 
    "subject": "Subject", 
    "body": "Body" 
}