@baseUrl=http://127.0.0.1:5000/

GET {{baseUrl}}

###

POST {{baseUrl}}/sendmail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.7Eifl29nrN-4r-806eT7cfyPxJKxmLX4kFnsWENwZjg

{ 
    "to": "user@server.domain", 
    "subject": "Subject", 
    "body": "Body" 
}